version: '3.8'

services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    image: php:7.0-apache
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html/

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_DATABASE: cdx-repair
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
       - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8081:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db

# volumes:
#   mysql-data:
